using UnityEngine;
using System.Collections;

public class DragAndDrop : MonoBehaviour
{
    private Camera _cam;
    private GridManager _grid;
    private PizzaPlate _pizzaPlate;

    private Transform _currentGridSlot;
    private Vector3 _startPosition;
    private Vector3 _originalScale;

    private bool _isDragging = false;
    private PizzaSpawner _mySpawner;
    private Transform _tempPreviousGridSlot;

    [Header("Cấu Hình Kéo Thả")]
    public float snapDist = 1.3f;
    public float dragHeight = 0.5f;

    // Biến quản lý Ghost Preview
    private GameObject _ghostMeshInstance;
    private Material _ghostMaterial;
    private static Material _sharedGhostMaterial;

    private Quaternion _originalRotation;

    void Start()
    {
        _cam = Camera.main;
        _grid = FindFirstObjectByType<GridManager>();
        _pizzaPlate = GetComponent<PizzaPlate>();
        _startPosition = transform.position;
        _originalScale = transform.localScale;
        _originalRotation = transform.rotation;

        CreateGhostMaterial();
    }

    public void AssignSpawner(PizzaSpawner spawner)
    {
        _mySpawner = spawner;
    }

    private void CreateGhostMaterial()
    {
        if (_sharedGhostMaterial != null)
        {
            _ghostMaterial = _sharedGhostMaterial;
            return;
        }

        // Tạo vật liệu Standard bán trong suốt (Ghost Material) chuẩn công nghiệp bằng code
        Shader standardShader = Shader.Find("Standard");
        if (standardShader == null) standardShader = Shader.Find("Legacy Shaders/Transparent/Diffuse");
        
        _sharedGhostMaterial = new Material(standardShader);
        _sharedGhostMaterial.name = "GhostMaterial_AutoGenerated";
        
        // Cấu hình chế độ Transparent Blend cho Standard Shader
        _sharedGhostMaterial.SetFloat("_Mode", 3f);
        _sharedGhostMaterial.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
        _sharedGhostMaterial.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
        _sharedGhostMaterial.SetInt("_ZWrite", 0);
        _sharedGhostMaterial.DisableKeyword("_ALPHATEST_ON");
        _sharedGhostMaterial.EnableKeyword("_ALPHABLEND_ON");
        _sharedGhostMaterial.DisableKeyword("_ALPHAPREMULTIPLY_ON");
        _sharedGhostMaterial.renderQueue = 3000;
        _sharedGhostMaterial.color = new Color(0.3f, 1f, 0.4f, 0.45f); // Màu xanh lá bán trong suốt báo hiệu vị trí hợp lệ

        _ghostMaterial = _sharedGhostMaterial;
    }

    void Update()
    {
        // Quản lý kéo thả tương thích 100% với cả New Input System và Legacy Input Manager
        HandlePointerInput();
    }

    private void HandlePointerInput()
    {
        // Nếu không ở trạng thái Playing (chỉ chặn nếu GameManager tồn tại)
        if (GameManager.Instance != null && GameManager.Instance.CurrentState != GameState.Playing) return;
        if (_pizzaPlate != null && (_pizzaPlate.IsMerging || _pizzaPlate.IsBloomed)) return;

        bool pointerDown = false;
        bool pointerActive = false;
        bool pointerUp = false;
        Vector2 screenPos = Vector2.zero;

        // Tự động sử dụng API của New Input System nếu được bật trong cài đặt Unity Player
#if ENABLE_INPUT_SYSTEM
        var pointer = UnityEngine.InputSystem.Pointer.current;
        if (pointer != null)
        {
            pointerDown = pointer.press.wasPressedThisFrame;
            pointerActive = pointer.press.isPressed;
            pointerUp = pointer.press.wasReleasedThisFrame;
            screenPos = pointer.position.ReadValue();
        }
        else
#endif
        {
            pointerDown = Input.GetMouseButtonDown(0);
            pointerActive = Input.GetMouseButton(0);
            pointerUp = Input.GetMouseButtonUp(0);
            screenPos = Input.mousePosition;
        }

        // Chặn kéo thả nếu người chơi nhấp chuột qua các nút UI Canvas phẳng
        if (pointerDown && UnityEngine.EventSystems.EventSystem.current != null && 
            UnityEngine.EventSystems.EventSystem.current.IsPointerOverGameObject())
        {
            return;
        }

        if (pointerDown && !_isDragging)
        {
            if (_cam == null) _cam = Camera.main;
            if (_cam == null) return;

            Ray ray = _cam.ScreenPointToRay(screenPos);
            if (Physics.Raycast(ray, out RaycastHit hit))
            {
                // Nhấp đúng vào đĩa bánh này hoặc con của nó
                if (hit.transform == this.transform || hit.transform.IsChildOf(this.transform))
                {
                    StartDragAndDrop();
                }
            }
        }
        else if (pointerActive && _isDragging)
        {
            if (_cam == null) _cam = Camera.main;
            if (_cam == null) return;

            Plane horizontalPlane = new Plane(Vector3.up, new Vector3(0, dragHeight, 0));
            Ray ray = _cam.ScreenPointToRay(screenPos);

            if (horizontalPlane.Raycast(ray, out float distance))
            {
                Vector3 targetPoint = ray.GetPoint(distance);
                transform.position = targetPoint;

                // Xử lý Snapping và Ghost Preview
                UpdateGhostPreviewAndSnapping(targetPoint);
            }
        }
        else if (pointerUp && _isDragging)
        {
            _isDragging = false;

            // Huỷ Ghost Mesh ngay khi thả tay
            DestroyGhostMesh();

            // Xử lý thả bánh xuống lưới
            DropPlate();
        }
    }

    private void StartDragAndDrop()
    {
        _isDragging = true;
        _startPosition = transform.position; // Cập nhật toạ độ gốc trước khi kéo

        // Nếu nhấc đĩa lên khỏi ô lưới đang nằm (cho phép di chuyển đĩa trên lưới)
        if (_currentGridSlot != null && _grid != null)
        {
            _tempPreviousGridSlot = _currentGridSlot;
            _grid.SetPlateInSlot(_currentGridSlot, null);
            _currentGridSlot = null;
            if (_pizzaPlate != null) _pizzaPlate.SetGridSlot(null);
        }
        else
        {
            _tempPreviousGridSlot = null;
        }

        // HIỆU ỨNG TWEEN NHẤC ĐĨA: Phóng to nhẹ và nâng lên khỏi mặt bàn
        StopAllCoroutines();
        StartCoroutine(TweenLiftRoutine(true));

        // Sinh Ghost Mesh xem trước
        SpawnGhostMesh();
    }

    private void SpawnGhostMesh()
    {
        if (_ghostMeshInstance != null) Destroy(_ghostMeshInstance);

        // Tạo Ghost Mesh bằng cách copy lại mesh đĩa hiện tại
        MeshFilter mf = GetComponentInChildren<MeshFilter>();
        if (mf != null)
        {
            _ghostMeshInstance = new GameObject("Ghost_Preview_Plate");
            MeshFilter ghostFilter = _ghostMeshInstance.AddComponent<MeshFilter>();
            ghostFilter.sharedMesh = mf.sharedMesh;

            MeshRenderer ghostRenderer = _ghostMeshInstance.AddComponent<MeshRenderer>();
            ghostRenderer.sharedMaterial = _ghostMaterial;

            // Đồng bộ kích thước ban đầu của đĩa
            _ghostMeshInstance.transform.localScale = mf.transform.lossyScale;
            _ghostMeshInstance.SetActive(false); // Ẩn đi, chỉ hiện khi snap gần ô lưới
        }
    }

    private void DestroyGhostMesh()
    {
        if (_ghostMeshInstance != null)
        {
            Destroy(_ghostMeshInstance);
            _ghostMeshInstance = null;
        }
    }

    private void UpdateGhostPreviewAndSnapping(Vector3 dragPos)
    {
        if (_grid == null || _grid.generatedSlots == null) return;

        Transform closestSlot = null;
        float closestDistance = Mathf.Infinity;

        // Tìm ô lưới gần nhất
        foreach (var slot in _grid.generatedSlots)
        {
            float d = Vector3.Distance(new Vector3(dragPos.x, 0, dragPos.z), new Vector3(slot.position.x, 0, slot.position.z));
            if (d < closestDistance)
            {
                closestDistance = d;
                closestSlot = slot;
            }
        }

        // Nếu ô lưới gần nhất nằm trong bán kính Snap và đang trống
        if (closestSlot != null && closestDistance < snapDist && _grid.GetPlateInSlot(closestSlot) == null)
        {
            if (_ghostMeshInstance != null)
            {
                _ghostMeshInstance.transform.position = closestSlot.position + Vector3.up * 0.05f;
                _ghostMeshInstance.transform.rotation = _originalRotation;
                _ghostMeshInstance.SetActive(true);
            }

            // Gợi ý cho người chơi bằng cách hút nhẹ đĩa bánh về hướng ô Snap
            Vector3 snapTarget = closestSlot.position + Vector3.up * dragHeight;
            transform.position = Vector3.Lerp(transform.position, snapTarget, 0.25f);
        }
        else
        {
            if (_ghostMeshInstance != null)
            {
                _ghostMeshInstance.SetActive(false);
            }
        }
    }

    private void DropPlate()
    {
        if (_grid == null || _grid.generatedSlots == null)
        {
            RestorePreviousGridSlot();
            StartCoroutine(TweenBackRoutine());
            return;
        }

        Transform closestSlot = null;
        float closestDistance = Mathf.Infinity;

        foreach (var slot in _grid.generatedSlots)
        {
            float d = Vector3.Distance(new Vector3(transform.position.x, 0, transform.position.z), new Vector3(slot.position.x, 0, slot.position.z));
            if (d < closestDistance)
            {
                closestDistance = d;
                closestSlot = slot;
            }
        }

        // Nếu thả đĩa hợp lệ
        if (closestSlot != null && closestDistance < snapDist && _grid.GetPlateInSlot(closestSlot) == null)
        {
            // Thiết lập vị trí Snap chuẩn xác
            transform.position = closestSlot.position + Vector3.up * 0.05f;
            transform.rotation = _originalRotation;

            _grid.SetPlateInSlot(closestSlot, transform);
            _currentGridSlot = closestSlot;
            
            if (_pizzaPlate != null)
            {
                _pizzaPlate.SetGridSlot(closestSlot);
            }

            _tempPreviousGridSlot = null;

            // HIỆU ỨNG SQUASH & STRETCH KHI ĐẶT: Tạo cảm giác trọng lượng của đĩa
            StartCoroutine(TweenDropRoutine());

            // Chỉ refill spawner khi đĩa được đặt vào lưới thành công
            if (_mySpawner != null)
            {
                _mySpawner.OnPlateTaken();
                _mySpawner = null;
            }

            // Kích hoạt Sự Kiện Đặt Thành Công (FSM chuyển CheckingCombo)
            GameEvents.TriggerPlatePlaced(closestSlot, transform);
        }
        else
        {
            // ĐẶT SAI Ô: Rung lắc lắc cảnh báo lỗi trực quan và bay về chỗ cũ
            RestorePreviousGridSlot();
            StartCoroutine(ErrorShakeAndTweenBackRoutine());
        }
    }

    private void RestorePreviousGridSlot()
    {
        if (_tempPreviousGridSlot != null && _grid != null)
        {
            _currentGridSlot = _tempPreviousGridSlot;
            _grid.SetPlateInSlot(_currentGridSlot, transform);
            if (_pizzaPlate != null) _pizzaPlate.SetGridSlot(_currentGridSlot);
            _tempPreviousGridSlot = null;
        }
    }

    // TWEEN NHẤC ĐĨA BÁNH (Hút tay khi nhấc)
    private IEnumerator TweenLiftRoutine(bool isLift)
    {
        Vector3 targetScale = isLift ? _originalScale * 1.12f : _originalScale;
        float elapsed = 0f;
        float duration = 0.15f;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / duration;
            transform.localScale = Vector3.Lerp(transform.localScale, targetScale, t);
            yield return null;
        }
        transform.localScale = targetScale;
    }

    // TWEEN ĐÀN HỒI (SQUASH & STRETCH) KHI ĐẶT BÁNH XUỐNG BÀN
    private IEnumerator TweenDropRoutine()
    {
        float elapsed = 0f;

        // Bóp dẹt Y, phình X-Z tạo phản lực đàn hồi
        Vector3 squashScale = new Vector3(_originalScale.x * 1.18f, _originalScale.y * 0.65f, _originalScale.z * 1.18f);

        while (elapsed < 0.1f)
        {
            elapsed += Time.deltaTime;
            transform.localScale = Vector3.Lerp(_originalScale, squashScale, elapsed / 0.1f);
            yield return null;
        }

        elapsed = 0f;
        // Kéo giãn nhẹ Y, co dẹt X-Z để bung nảy
        Vector3 stretchScale = new Vector3(_originalScale.x * 0.9f, _originalScale.y * 1.15f, _originalScale.z * 0.9f);
        while (elapsed < 0.1f)
        {
            elapsed += Time.deltaTime;
            transform.localScale = Vector3.Lerp(squashScale, stretchScale, elapsed / 0.1f);
            yield return null;
        }

        elapsed = 0f;
        // Hồi vị về ban đầu mượt mà
        while (elapsed < 0.15f)
        {
            elapsed += Time.deltaTime;
            transform.localScale = Vector3.Lerp(stretchScale, _originalScale, elapsed / 0.15f);
            yield return null;
        }

        transform.localScale = _originalScale;
    }

    // RUNG LẮC BÁO LỖI VÀ TWEENBACK VỀ VỊ TRÍ CŨ
    private IEnumerator ErrorShakeAndTweenBackRoutine()
    {
        // 1. Rung lắc tại chỗ (Shake Error)
        float elapsed = 0f;
        float shakeDuration = 0.25f;
        float shakeMagnitude = 0.08f;
        Vector3 shakeStartPos = transform.position;

        while (elapsed < shakeDuration)
        {
            elapsed += Time.deltaTime;
            float randomX = Random.Range(-1f, 1f) * shakeMagnitude;
            float randomZ = Random.Range(-1f, 1f) * shakeMagnitude;
            transform.position = new Vector3(shakeStartPos.x + randomX, shakeStartPos.y, shakeStartPos.z + randomZ);
            yield return null;
        }

        transform.position = shakeStartPos;

        // 2. Bay ngược về vị trí cũ (Tweenback)
        elapsed = 0f;
        float flyBackDuration = 0.25f;
        Vector3 currentPos = transform.position;

        while (elapsed < flyBackDuration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / flyBackDuration;
            // Dùng nội suy Bezier nhẹ hoặc Lerp nâng Y lên tí tạo quỹ đạo bay vòng về
            Vector3 midPoint = (currentPos + _startPosition) / 2f + Vector3.up * 0.6f;
            Vector3 m1 = Vector3.Lerp(currentPos, midPoint, t);
            Vector3 m2 = Vector3.Lerp(midPoint, _startPosition, t);
            transform.position = Vector3.Lerp(m1, m2, t);
            transform.localScale = Vector3.Lerp(transform.localScale, _originalScale, t);
            yield return null;
        }

        transform.position = _startPosition;
        transform.localScale = _originalScale;
    }

    private IEnumerator TweenBackRoutine()
    {
        float elapsed = 0f;
        float duration = 0.2f;
        Vector3 currentPos = transform.position;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / duration;
            transform.position = Vector3.Lerp(currentPos, _startPosition, t);
            transform.localScale = Vector3.Lerp(transform.localScale, _originalScale, t);
            yield return null;
        }

        transform.position = _startPosition;
        transform.localScale = _originalScale;
    }

    void OnDestroy()
    {
        DestroyGhostMesh();
    }
}